version: 2.1
jobs:
  build:
    docker: 
      - image: kuronekomichael/flutter:jenkins-slave
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello circleci" # run the `echo` command