version: 2.1
jobs:
  build:
    docker: 
      - image: kuronekomichael/flutter:jenkins-slave
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: 'Changing Directory'
          command: |
            ls
            cd client
            ls
      - run: flutter test
