version: 2.1
jobs:
  build:
    docker: 
      - image: kuronekomichael/flutter:jenkins-slave
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: 'Running Flutter Test'
          command: |
            cd client
            flutter upgrade
            flutter test
